language: python
python:
  - 2.7
notifications:
    - rowanc1@gmail.com
    # - dwfmarchant@gmail.com
    # - sgkang09@gmail.com
    # - lindseyheagy@gmail.com

# Setup anaconda
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.3.0-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.3.0-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  # Remove this when SimPEG is on pip
  - cd ../
  - git clone https://github.com/simpeg/simpeg.git
  - cd simpeg/SimPEG/
  - python setup.py
  - cd ../../
  - export PYTHONPATH=/home/travis/build/simpeg/simpeg:$PYTHONPATH
  - cd simpegem

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
  # Coverage packages are on dan_blanchard's binstar channel
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - pip install -r requirements.txt
  # - python setup.py install

# Run test
script:
  - nosetests --with-cov --cov simpegem --cov-config .coveragerc --logging-level=INFO

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
